BLC/BLC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('logistics.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BLC/logistics/urls.py
from django.urls import path
from logistics import views

urlpatterns = [
    ### Login & Logout Url ###
    path('', views.Login_Page.as_view(), name='login_page'),
    path('logout', views.Logout_Page.as_view(), name='logout_page'),
    ### Dashboard Url ###
    path('dashboard', views.Dashboard_Page.as_view(), name='dashboard'),
    ### Customer Url ###
    path('customer-list', views.CustomerListView.as_view(), name='customer_list'),
    path('customer-create', views.CustomerCreateView.as_view(), name='customer_create'),
    path('customer-edit/<int:pk>', views.CustomerUpdateView.as_view(), name='customer_edit'),
    path('customer-delete/<int:pk>', views.CustomerDeleteView.as_view(), name='customer_delete'),
    ### Destination Url ###
    path('destination-list', views.DestinationListView.as_view(), name='destination_list'),
    path('destination-create', views.DestinationCreateView.as_view(), name='destination_create'),
    path('destination-edit/<int:pk>', views.DestinationUpdateView.as_view(), name='destination_edit'),
    path('destination-delete/<int:pk>', views.DestinationDeleteView.as_view(), name='destination_delete'),
    ### Vehicle Url ###
    path('vehicle-list', views.VehicleListView.as_view(), name='vehicle_list'),
    path('vehicle-create', views.VehicleCreateView.as_view(), name='vehicle_create'),
    path('vehicle-edit/<int:pk>', views.VehicleUpdateView.as_view(), name='vehicle_edit'),
    path('vehicle-delete/<int:pk>', views.VehicleDeleteView.as_view(), name='vehicle_delete'),
    ### Driver Url ###
    path('driver-list', views.DriverListView.as_view(), name='driver_list'),
    path('driver-create', views.DriverCreateView.as_view(), name='driver_create'),
    path('driver-edit/<int:pk>', views.DriverUpdateView.as_view(), name='driver_edit'),
    path('driver-delete/<int:pk>', views.DriverDeleteView.as_view(), name='driver_delete'),
    ### Routes Url ###
    path('route-list', views.RouteListView.as_view(), name='route_list'),
    path('route-create', views.RouteCreateView.as_view(), name='route_create'),
    path('route-edit/<int:pk>', views.RouteUpdateView.as_view(), name='route_edit'),
    path('route-delete/<int:pk>', views.RouteDeleteView.as_view(), name='route_delete'),
    ### Trip Url ###
    path('ongoing-trip-list', views.OngoingTripListView.as_view(), name='ongoing_trip_list'),
    path('completed-trip-list', views.CompletedTripListView.as_view(), name='completed_trip_list'),
    path('trip-create', views.TripCreateView.as_view(), name='trip_create'),
    path('trip-edit/<int:pk>', views.TripUpdateView.as_view(), name='trip_edit'),
    path('trip-delete/<int:pk>', views.TripDeleteView.as_view(), name='trip_delete'),
    path('trip-details/<int:pk>', views.TripDetailView.as_view(), name='trip_details'),
    path('trip-pending', views.TripPendingListView, name='trip_pending'),
    path('trip-end/<int:pk>', views.TripEndView, name='trip_end'),
    path('trip-close', views.TripCloseView.as_view(), name='trip_close'),
    path('product-autocomplete', views.get_product_listing, name='product_autocomplete'),
    path('get-available-vehicles', views.get_available_vehicles, name='get_available_vehicles'),
    ### Fuel Url ###
    path('fuel-list', views.FuelListView.as_view(), name='fuel_list'),
    path('fuel-create', views.FuelCreateView.as_view(), name='fuel_create'),
    path('fuel-edit/<int:pk>', views.FuelUpdateView.as_view(), name='fuel_edit'),
    path('fuel-delete/<int:pk>', views.FuelDeleteView.as_view(), name='fuel_delete'),
    path('station-autocomplete', views.get_station_listing, name='station_autocomplete'),
    ### Wheels Url ###
    path('wheel-list/<int:pk>', views.WheelListView.as_view(), name='wheel_list'),
    path('wheel-create/<int:pk>', views.WheelCreateView.as_view(), name='wheel_create'),
    path('wheel-edit/<int:pk>', views.WheelUpdateView.as_view(), name='wheel_edit'),
    ### Maintenance Url ###
    path('maintenance-list', views.MaintenanceListView.as_view(), name='maintenance_list'),
    path('maintenance-create', views.MaintenanceCreateView.as_view(), name='maintenance_create'),
    path('maintenance-edit/<int:pk>', views.MaintenanceUpdateView.as_view(), name='maintenance_edit'),
    path('maintenance-delete/<int:pk>', views.MaintenanceDeleteView.as_view(), name='maintenance_delete'),
    path('maintenance-autocomplete', views.get_maintenance_listing, name='maintenance_autocomplete'),
]

BLC/logistics/models.py
from operator import mod
from django.db import models
from django.core.validators import RegexValidator, MinValueValidator
from decimal import *
from datetime import datetime,timedelta,date
# Create your models here.
class CaseInsensitiveFieldMixin:
    """
    Field mixin that uses case-insensitive lookup alternatives if they exist.
    """

    LOOKUP_CONVERSIONS = {
        'exact': 'iexact',
        'contains': 'icontains',
        'startswith': 'istartswith',
        'endswith': 'iendswith',
        'regex': 'iregex',
    }

    def get_lookup(self, lookup_name):
        converted = self.LOOKUP_CONVERSIONS.get(lookup_name, lookup_name)
        return super().get_lookup(converted)

class CICharField(CaseInsensitiveFieldMixin, models.CharField):
    pass

# Regular Expression for Vehicle Number #
vehicle_number = RegexValidator(r'^[A-Za-z]{2}-[0-9]{2}-[A-Za-z]{2}-[0-9]{4}')
mobile_number = RegexValidator(r'^[0-9]{10}')


### CUSTOMER MODEL ###
class Customer(models.Model):
    name = CICharField(max_length=255, unique=True)
    address = models.TextField(max_length=255)
    state = models.CharField(max_length=255)
    
    class Meta:
        verbose_name = "Customer"
        verbose_name_plural = "Customers"
    
    def __str__(self):
        return self.name    
    
### DESTINATION MODEL ###
class Destination(models.Model):
    name = CICharField(max_length=255, unique=True)
    address = models.TextField(max_length=255)
    state = models.CharField(max_length=255)
    
    class Meta:
        verbose_name = "Destination"
        verbose_name_plural = "Destinations"
    
    def __str__(self):
        return self.name    

### DRIVER MODEL ###    
class Driver(models.Model):
    full_name = models.CharField(max_length=255)
    contact = models.CharField(max_length=10, unique=True, validators=[mobile_number])
    available = models.BooleanField(default=True)
    class Meta:
        verbose_name = "Driver"
        verbose_name_plural = "Drivers"
    
    def __str__(self):
        return self.full_name
    
    
### AXLE CHOICES ###
class Axle(models.IntegerChoices):
    WL12 = 12, '12WL'
    WL14 = 14, '14WL'
    WL16 = 16, '16WL'
    WL22 = 22, '22WL'
       
### VEHICLE MODEL ###
class Vehicle(models.Model):
    vehicle_number = CICharField(max_length=13, unique=True, validators=[vehicle_number])
    purchase_date = models.DateField()
    axle = models.IntegerField(choices=Axle.choices)
    fuel_capacity = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    load_capacity = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    available = models.BooleanField(default=True)
    
    class Meta:
        verbose_name = "Vehicle"
        verbose_name_plural = "Vehicles"
        
    def __str__(self):
        return self.vehicle_number
    
### TRIP DISTANCE MODEL ###
class Route(models.Model):
    customer = models.ForeignKey('logistics.Customer', on_delete=models.CASCADE, related_name='route_customers')    
    destination = models.ForeignKey('logistics.Destination', on_delete=models.CASCADE, related_name='route_destinations')
    distance = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    fuel_required = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    
    class Meta:
        verbose_name = "Route"
        verbose_name_plural = "Routes"
    
    def __str__(self):
        return '%s --->To---> %s' % (self.customer, self.destination)

### WHEEL USAGE MODEL ###
class Wheel(models.Model):
    vehicle_number = models.ForeignKey('logistics.Vehicle', on_delete=models.PROTECT, related_name='vehicle_wheels')
    serial_number = models.CharField(max_length=255, unique=True, blank=True, null=True)
    purchase_date = models.DateField(blank=True, null=True)
    running_life = models.IntegerField(validators=[MinValueValidator(1)],blank=True, null=True)
    usage = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))], default=0)
    
    class Meta:
        verbose_name = "Wheel"
        verbose_name_plural = "Wheels"
        
    def __str__(self):
        return '%s || %s' % (self.vehicle_number, self.serial_number)    
    
    @property
    def remaining_life(self):
        return self.running_life - self.usage
        
    @property
    def remaining_life_percentage(self):
        return (self.running_life - self.usage)/self.running_life*100
                    
    
### VEHICLE MAINTENANCE MODEL ###
class VehicleMaintenance(models.Model):
    vehicle_number = models.ForeignKey('logistics.Vehicle', on_delete=models.PROTECT, related_name='vehicle_maintenance')
    start_date = models.DateField()    
    end_date = models.DateField()
    description = models.TextField(max_length=1000)
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    invoice = models.ImageField(blank=True, upload_to='maintenance_bills')
    
    class Meta:
        verbose_name = "VehicleMaintenance"
        verbose_name_plural = "VehicleMaintenances"
        
### TRIP MODEL ###
def increment_trip_number():
  last_no = Trip.objects.all().order_by('id').last()
  if not last_no:
    return 'BLC-' + str(date.today().month).zfill(2) +'-'+ str(date.today().year) + '-' + '0001'
  no_int = int(last_no.trip_id[-4:])
  new_no_int = no_int + 1
  new_no_id = 'BLC-' + str(date.today().month).zfill(2) +'-'+ str(date.today().year) +'-'+ str(new_no_int).zfill(4)  
  return new_no_id

class Trip(models.Model):
    trip_id = CICharField(max_length=50, blank=True, unique=True, default=increment_trip_number)
    shipment_no = models.CharField(max_length=255)
    route = models.ForeignKey('logistics.Route', on_delete=models.PROTECT, related_name='trip_route')
    vehicle_number = models.ForeignKey('logistics.Vehicle',on_delete=models.PROTECT, related_name='vehicle_trips')    
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    driver = models.ForeignKey('logistics.Driver', on_delete=models.PROTECT, related_name='driver_trips')
    product = models.CharField(max_length=255)
    load = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    eway_bill = models.ImageField(blank=True, upload_to='eway_bills')
    driver_advance = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    fuel_advance = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    message_id = models.PositiveIntegerField(validators=[MinValueValidator(1)], default=1)
    complete = models.BooleanField(default=False)
    
    class Meta:
        verbose_name = "Trip"
        verbose_name_plural = "Trips"
        
    def __str__(self):
        return '%s || %s' % (self.trip_id, self.route)    
    
### FUEL MODEL ###
class Fuel(models.Model):
    vehicle_number = models.ForeignKey('logistics.Vehicle', on_delete=models.PROTECT, related_name='vehicle_fuel')
    driver = models.ForeignKey('logistics.Driver', on_delete=models.PROTECT, related_name='driver_fuel')
    date = models.DateField()
    station = models.CharField(max_length=255)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])    
    rate = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    bill = models.ImageField(blank=True, upload_to='fuel_bills')
    
    class Meta:
        verbose_name = "Fuel"
        verbose_name_plural = "Fuels"
        
    def __str__(self):
        return self.date + " || " + self.station + " || " + str(self.quantity)
    
### TRIP EXPENSE MODEL ###
class TripAmount(models.Model):
    trip_id = models.ForeignKey('logistics.Trip',on_delete=models.CASCADE, related_name='trip_amounts')
    freight_rate = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    freight_amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])
    driver_payment = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))], default=0.0)
    loading_payment = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))], default=0.0)
    unloading_payment = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))], default=0.0)
    rto_payment = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))], default=0.0)
    toll_charges = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))], default=0.0)
    other_charges = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))], default=0.0)
    
    class Meta:
        verbose_name = "TripAmount"
        verbose_name_plural = "TripAmounts"
    
    def __str__(self):
        return self.trip_id
            

BLC/logistics/templates/logistics/customer_edit.html
{% load widget_tweaks %}
<form method="post" action="">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Update Customer</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        {% if form.non_field_errors %}
            <div class="alert alert-block alert-danger invalid">
                {{form.non_field_errors}}
            </div>
        {% endif %}

        {% if form.name.errors %}
            {% for error in form.name.errors %}
                <div class="form-group invalid mb-2">
                    <label for="{{form.name.id_for_label}}"><strong>Customer Name<span class="asteriskfield"> *</span> </strong></label>
                    {% render_field form.name class+='form-control is-invalid' %}
                    <div class="invalid-feedback">
                        <strong>{{error}}</strong>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        <div class="form-group mb-2">
            <label for="{{form.name.id_for_label}}"><strong>Customer Name<span class="asteriskfield"> *</span> </strong></label>
            {% render_field form.name class+='form-control' %}
        </div>
        {% endif %}

        {% if form.address.errors %}
            {% for error in form.address.errors %}
                <div class="form-group invalid mb-2">
                    <label for="{{form.address.id_for_label}}"><strong>Address<span class="asteriskfield"> *</span> </strong></label>
                    {% render_field form.address class+='form-control is-invalid' %}
                    <div class="invalid-feedback">
                        <strong>{{error}}</strong>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        <div class="form-group mb-2">
            <label for="{{form.address.id_for_label}}"><strong>Address<span class="asteriskfield"> *</span> </strong></label>
            {% render_field form.address class+='form-control' %}
        </div>
        {% endif %}

        {% if form.state.errors %}
            {% for error in form.state.errors %}
                <div class="form-group invalid mb-2">
                    <label for="{{form.state.id_for_label}}"><strong>State<span class="asteriskfield"> *</span> </strong></label>
                    {% render_field form.state class+='form-control is-invalid' %}
                    <div class="invalid-feedback">
                        <strong>{{error}}</strong>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        <div class="form-group mb-2">
            <label for="{{form.state.id_for_label}}"><strong>State<span class="asteriskfield"> *</span> </strong></label>
            {% render_field form.state class+='form-control' %}
        </div>
        {% endif %}
    </div>      
    <div class="modal-footer">
    <button type="submit" class="btn text-white" style="background-color:#264653;">Update</button>
    </div>
</form>

BLC/logistics/templates/logistics/maintenance_list.html
{% extends 'base.html' %}
{% block title %}Vehicle Maintenance{% endblock title %}

{% block content %}
<div class="modal fade" id="maintenance-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content"></div>
    </div>
</div>
<div class="fade-in">
    <div class="row mx-2 mb-3 mt-3">
        {% comment %} <h4 class="">LIST OF CUSTOMERS</h4> {% endcomment %}
    </div>
    
    <div class="row">
        <div class="col-6 mx-2 mb-1">
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert" id="message_container">
                    <strong>{{message}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="row">
        <div class="col-12 mx-2 my-0 align-middle">
            <a type="button" class="btn btn-sm my-3 text-white" style="float:left;background-color:#264653;" href="{% url 'maintenance_create' %}">Add Maintenance</a>
            <input type="search" placeholder="Search..." class="form-control search-input my-3" data-table="maintenance-list"/ style="float:right;width:300px;margin-left:auto;">  
        </div>
    </div>

    <div class="row mt-1">
        <div class="col-12 mx-2">
            <table class="table table-hover caption-top rounded maintenance-list">
                <caption class="fs-3">Vehicle Maintenance</caption>
                <thead class="text-white" style="background-color:#2a9d8f">
                    <tr>
                        <th scope="col"class="align-middle">Vehicle Number</th>
                        <th scope="col"class="text-center align-middle">Start Date</th>
                        <th scope="col"class="text-center align-middle">End Date</th>
                        <th scope="col"class="align-middle">Maitenance Description</th>
                        <th scope="col"class="text-center align-middle">Amount</th>
                        <th scope="col"class="text-center align-middle">Invoice</th>
                        <th scope="col"class="text-center align-middle">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in vehiclemaintenance_list %}
                    <tr>
                        <td class="align-middle">{{item.vehicle_number.vehicle_number}}</td>
                        <td class="text-center align-middle">{{item.start_date}}</td>
                        <td class="text-center align-middle">{{item.end_date}}</td>
                        <td class="align-middle">{{item.description}}</td>
                        <td class="text-center align-middle">{{item.amount}}</td>
                        <td class="text-center align-middle"><a href={% if item.invoice %}"{{item.invoice.url}}"{% else %}"#"{% endif %}><img alt="Not Uploaded" width="75" height="75"  src={% if item.invoice %}"{{item.invoice.url}}"{% endif %}></img></a></td>
                        <td class="align-middle text-center">    
                            <a type="button" href="{% url 'maintenance_edit' item.pk %}">
                                <span class="material-icons align-middle text-center fw-bold" style="color:#e9c46a;">edit</span>
                            </a>
                            <a type="button" class="bs-modal" data-form-url="{% url 'maintenance_delete' item.pk %}">
                                <span class="material-icons align-middle text-center fw-bold" style="color:#e76f51;">delete</span>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

{% block customjs %}
<script>
    $(function(){
        $(".bs-modal").each(function(){
            $(this).modalForm({
                formURL: $(this).data('form-url'),
                modalID: '#maintenance-modal'
            });
        });
    });
</script>
<script>
    var message_ele = document.getElementById("message_container");
    setTimeout(function(){
        message_ele.style.display = "none";
    }, 6000);
</script>

<script>
    (function(document) {
        'use strict';

        var TableFilter = (function(myArray) {
            var search_input;

            function _onInputSearch(e) {
                search_input = e.target;
                var tables = document.getElementsByClassName(search_input.getAttribute('data-table'));
                myArray.forEach.call(tables, function(table) {
                    myArray.forEach.call(table.tBodies, function(tbody) {
                        myArray.forEach.call(tbody.rows, function(row) {
                            var text_content = row.textContent.toLowerCase();
                            var search_val = search_input.value.toLowerCase();
                            row.style.display = text_content.indexOf(search_val) > -1 ? '' : 'none';
                        });
                    });
                });
            }

            return {
                init: function() {
                    var inputs = document.getElementsByClassName('search-input');
                    myArray.forEach.call(inputs, function(input) {
                        input.oninput = _onInputSearch;
                    });
                }
            };
        })(Array.prototype);

        document.addEventListener('readystatechange', function() {
            if (document.readyState === 'complete') {
                TableFilter.init();
            }
        });

    })(document);
</script>

{% endblock customjs %}

BLC/logistics/templates/logistics/route_delete.html
{% load widget_tweaks %}
<form method="post" action="">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Delete Route</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <p>Are you sure you want to delete Route : <strong>{{route.customer.name}} To {{route.destination.name}}</strong> ?</p>
   
    </div>      
    <div class="modal-footer">
    <button type="submit" class="btn text-white" style="background-color:#e76f51;">Delete</button>
    </div>
</form>

BLC/logistics/templates/logistics/trip_ongoing_list.html
{% extends 'base.html' %}
{% block title %}On-Going Trips{% endblock title %}

{% block content %}
<div class="modal fade" id="trip-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content"></div>
    </div>
</div>
<div class="row mt-1">
    <div class="col-12">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a type="button" class="btn btn-warning mx-2" aria-current="page" href="{% url 'ongoing_trip_list' %}">On-Going Trips</a>
            </li>
            <li class="nav-item">
                <a type="button" class="btn btn-light mx-2" href="{% url 'completed_trip_list' %}" style="border:1px solid black;">Completed Trips</a>
            </li>
            <li class="nav-item">
                <a type="button" class="btn btn-light mx-2" href="{% url 'trip_create' %}" style="border:1px solid black;">Log New Trip</a>
            </li>
            <li class="nav-item">
                <a type="button" class="btn btn-light mx-2" href="{% url 'trip_pending' %}" style="border:1px solid black;">Close Trip</a>
            </li>
        </ul>
    </div>    
    <div class="col-12 mx-2">
        <hr style="height:2px;">
    </div>
</div>    

<div class="fade-in">
    <div class="row">
        <div class="col-6 mx-2 mb-1">
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert" id="message_container">
                    <strong>{{message}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="row">
        <div class="col-12 mx-2 my-0 align-middle">
            <input type="search" placeholder="Search..." class="form-control search-input my-1" data-table="trip-list"/ style="float:right;width:300px;margin-left:auto;">  
        </div>
    </div>

    <div class="row mt-1">
        <div class="col-12 mx-2">
            <table class="table table-hover caption-top rounded trip-list">
                <caption class="fs-3">ON-GOING TRIPS</caption>
                <thead class="text-grey" style="background-color:#ade8f4">
                    <tr>
                        <th scope="col"class="align-middle">Trip ID</th>
                        <th scope="col"class="text-center align-middle">Start Date</th>
                        <th scope="col"class="text-center align-middle">Source</th>
                        <th scope="col"class="text-center align-middle">Destination</th>
                        <th scope="col"class="text-center align-middle">Vehicle</th>
                        <th scope="col"class="text-center align-middle">Driver</th>
                        <th scope="col"class="text-center align-middle">Product</th>
                        <th scope="col"class="text-center align-middle">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in trip_list %}
                    <tr>
                        <td class="align-middle">{{item.trip_id}}</td>
                        <td class="text-center align-middle">{{item.start_date|date:'d M Y'}}</td>
                        <td class="text-center align-middle">{{item.route.customer.name}}</td>
                        <td class="text-center align-middle">{{item.route.destination.name}}</td>
                        <td class="text-center align-middle">{{item.vehicle_number.vehicle_number}}</td>
                        <td class="text-center align-middle">{{item.driver.full_name}}</td>
                        <td class="text-center align-middle">{{item.product}}</td>
                        <td class="align-middle text-center">
                            <a type="button" href="{% url 'trip_details' item.pk %}">
                                <span class="material-icons align-middle text-center text-warning">info</span>
                            </a>    
                            <a type="button" href="{% url 'trip_edit' item.pk %}">
                                <span class="material-icons align-middle text-center">edit</span>
                            </a>
                            <a type="button" class="bs-modal" data-form-url="{% url 'trip_delete' item.pk %}">
                                <span class="material-icons align-middle text-center text-danger">delete</span>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

{% block customjs %}
<script>
    var message_ele = document.getElementById("message_container");
    setTimeout(function(){
        message_ele.style.display = "none";
    }, 6000);
</script>

<script>
    $(function(){
        $(".bs-modal").each(function(){
            $(this).modalForm({
                formURL: $(this).data('form-url'),
                modalID: '#trip-modal'
            });
        });
    });
</script>


<script>
    (function(document) {
        'use strict';

        var TableFilter = (function(myArray) {
            var search_input;

            function _onInputSearch(e) {
                search_input = e.target;
                var tables = document.getElementsByClassName(search_input.getAttribute('data-table'));
                myArray.forEach.call(tables, function(table) {
                    myArray.forEach.call(table.tBodies, function(tbody) {
                        myArray.forEach.call(tbody.rows, function(row) {
                            var text_content = row.textContent.toLowerCase();
                            var search_val = search_input.value.toLowerCase();
                            row.style.display = text_content.indexOf(search_val) > -1 ? '' : 'none';
                        });
                    });
                });
            }

            return {
                init: function() {
                    var inputs = document.getElementsByClassName('search-input');
                    myArray.forEach.call(inputs, function(input) {
                        input.oninput = _onInputSearch;
                    });
                }
            };
        })(Array.prototype);

        document.addEventListener('readystatechange', function() {
            if (document.readyState === 'complete') {
                TableFilter.init();
            }
        });

    })(document);
</script>

{% endblock customjs %}